FROM ghcr.io/cyber-dojo-languages/javascript-node:256882c
LABEL maintainer=jon@jaggersoft.com

RUN mkdir /etc/mocha
WORKDIR /etc/mocha
COPY package.json .
RUN npm install

COPY red_amber_green.rb /usr/local/bin
