FROM cyberdojofoundation/javascript-node
LABEL maintainer=jon@jaggersoft.com

RUN npm install -global mocha chai sinon sinon-chai
ENV NODE_PATH /usr/local/lib/node_modules

COPY red_amber_green.rb /usr/local/bin
